#!/usr/bin/env python3
"""Generate placeholder SVG files for initial commit.
Run once after cloning to create initial SVG files.
The real files will be generated by the GitHub Actions workflow.
"""

import os

OUT_DIR = os.path.dirname(os.path.abspath(__file__))

# Placeholder ASCII portrait (simple stick figure)
ASCII_SVG = '''<svg xmlns="http://www.w3.org/2000/svg" width="400" height="500" viewBox="0 0 400 500" font-family="monospace">
<style>.a{fill:#6e7681}@media(prefers-color-scheme:dark){.a{fill:#c9d1d9}}</style>
<text x="200" y="60" class="a" font-size="24" text-anchor="middle">PURNASAI V</text>
<text x="200" y="120" class="a" font-size="12" text-anchor="middle">ML + Cybersecurity</text>
<text x="200" y="180" class="a" font-size="12" text-anchor="middle">Microsoft Student Chapter</text>
</svg>'''

# Helper SVG
HD_ABOUT_SVG = '''<svg xmlns="http://www.w3.org/2000/svg" width="620" height="26" viewBox="0 0 620 26" font-family="monospace">
<style>.emph{fill:#424a53}@media(prefers-color-scheme:dark){.emph{fill:#f0f6fc}}</style>
<line x1="162" y1="12.5" x2="620" y2="12.5" stroke="#d8dee4" stroke-width="1"/>
<text x="34" y="18" class="emph" font-size="16" font-weight="600">about</text>
</svg>'''

HD_STACK_SVG = '''<svg xmlns="http://www.w3.org/2000/svg" width="620" height="26" viewBox="0 0 620 26" font-family="monospace">
<style>.emph{fill:#424a53}@media(prefers-color-scheme:dark){.emph{fill:#f0f6fc}}</style>
<line x1="100" y1="12.5" x2="620" y2="12.5" stroke="#d8dee4" stroke-width="1"/>
<text x="34" y="18" class="emph" font-size="16" font-weight="600">stack</text>
</svg>'''

HD_PROJECTS_SVG = '''<svg xmlns="http://www.w3.org/2000/svg" width="620" height="26" viewBox="0 0 620 26" font-family="monospace">
<style>.emph{fill:#424a53}@media(prefers-color-scheme:dark){.emph{fill:#f0f6fc}}</style>
<line x1="136" y1="12.5" x2="620" y2="12.5" stroke="#d8dee4" stroke-width="1"/>
<text x="34" y="18" class="emph" font-size="16" font-weight="600">projects</text>
</svg>'''

HD_CONNECT_SVG = '''<svg xmlns="http://www.w3.org/2000/svg" width="620" height="70" viewBox="0 0 620 70" font-family="monospace">
<style>.emph{fill:#424a53}@media(prefers-color-scheme:dark){.emph{fill:#f0f6fc}}</style>
<text x="34" y="18" class="emph" font-size="16" font-weight="600">connect</text>
</svg>'''

BADGE_SVG_TEMPLATE = '''<svg xmlns="http://www.w3.org/2000/svg" width="180" height="28" viewBox="0 0 180 28" fill="none" font-family="JBMono,ui-monospace,SFMono-Regular,Menlo,Consolas,'Liberation Mono',monospace"><style>@font-face{font-family:JBMono;font-style:normal;font-weight:600;font-display:block;src:url(data:font/woff2;base64,) format('woff2')}.e-f{fill:#424a53}.u-s{stroke:#d8dee4}@media(prefers-color-scheme:dark){.e-f{fill:#f0f6fc}.u-s{stroke:#30363d}}</style><rect x="0" y="0" width="180" height="28" rx="6" class="u-s" fill="none" stroke-width="1"/><text x="90" y="19" class="e-f" font-size="13" font-weight="600" text-anchor="middle">{label}</text></svg>'''
BADGE_GITHUB_SVG = BADGE_SVG_TEMPLATE.format(label="GitHub")
BADGE_LINKEDIN_SVG = BADGE_SVG_TEMPLATE.format(label="LinkedIn")
BADGE_LEETCODE_SVG = BADGE_SVG_TEMPLATE.format(label="LeetCode")


def main():
    files = {
        "ascii.svg": ASCII_SVG,
        "hd-about.svg": HD_ABOUT_SVG,
        "hd-stack.svg": HD_STACK_SVG,
        "hd-projects.svg": HD_PROJECTS_SVG,
        "hd-connect.svg": HD_CONNECT_SVG,
        "badge-github.svg": BADGE_GITHUB_SVG,
        "badge-linkedin.svg": BADGE_LINKEDIN_SVG,
        "badge-leetcode.svg": BADGE_LEETCODE_SVG,
    }

    for filename, content in files.items():
        filepath = os.path.join(OUT_DIR, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Created {filename}")

    print("\n✓ Initial SVG files created!")
    print("✓ The GitHub Actions workflow will regenerate these with real data daily")
    print("\nTo generate an ASCII portrait from your photo:")
    print("  1. Install dependencies: pip install pillow numpy opencv-python-headless rembg onnxruntime")
    print("  2. Run: python scripts/make_portrait.py <your-photo.jpg>")
    print("  3. Run: python scripts/embed_portrait_font.py ascii.svg")


if __name__ == "__main__":
    main()
